### ISSUE TITLE
add github dependabot to keep maven plugins and libraries up to date

### ISSUE THREAD

**Issue by sellersj** [Akman/jpackage-maven-plugin#16]
This will help keep parts of the project up to date.

create a file .github/dependabot.yml
```
version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
```

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates
